var player1_name=localStorage.getItem("player1_name")
var player2_name=localStorage.getItem("player2_name")
p1score=0
p2score=0
document.getElementById("player1name").innerHTML=player1_name
document.getElementById("player2name").innerHTML=player2_name
document.getElementById("player1score").innerHTML=p1score
document.getElementById("player2score").innerHTML=p2score
document.getElementById("questionturn").innerHTML="Question Turn- "+player1_name
document.getElementById("answerturn").innerHTML="Answer Turn- "+player2_name